# -*- coding: utf-8 -*-
"""optimizers_with_bayesian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJWZDw9VoaMSLNVkhml-teXflEFNDNpK
"""

pip install bayesian-optimization

import numpy as np
from scipy.optimize import minimize
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
import csv
from scipy import linalg as LA
from scipy.interpolate import RBFInterpolator
from bayes_opt import BayesianOptimization
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C



#FGN : The problem expressed here in form   min f(x) : c(x)>=0

# Define the problem parameters
n = 5
mu = np.array([
    8.6033358901938017e-01, 3.4256184594817283e+00, 6.4372981791719468e+00,
    9.5293344053619631e+00, 1.2645287223856643e+01, 1.5771284874815882e+01,
    1.8902409956860023e+01, 2.2036496727938566e+01, 2.5172446326646664e+01,
    2.8309642854452012e+01, 3.1447714637546234e+01, 3.4586424215288922e+01,
    3.7725612827776501e+01, 4.0865170330488070e+01, 4.4005017920830845e+01,
    4.7145097736761031e+01, 5.0285366337773652e+01, 5.3425790477394663e+01,
    5.6566344279821521e+01, 5.9707007305335459e+01, 6.2847763194454451e+01,
    6.5988598698490392e+01, 6.9129502973895256e+01, 7.2270467060308960e+01,
    7.5411483488848148e+01, 7.8552545984242926e+01, 8.1693649235601683e+01,
    8.4834788718042290e+01, 8.7975960552493220e+01, 9.1117161394464745e+01
])

def objective(x):
    """Calculate the objective function value."""
    return np.sum(x**2)

def rho(x, mu_vals):
    """Calculate the rho function for given x and mu values."""
    n = len(x)
    result = np.zeros(len(mu_vals))
    for j in range(len(mu_vals)):
        exp_term = np.exp(-mu_vals[j]**2 * np.sum(x**2))
        sum_term = sum(2 * (-1)**(ii-1) * np.exp(-mu_vals[j]**2 * np.sum(x[ii-1:]**2))
                     for ii in range(2, n+1))
        result[j] = -(exp_term + sum_term + (-1)**n) / mu_vals[j]**2
    return result

def A(mu_val):
    """Calculate the A function for a given mu value."""
    return 2 * np.sin(mu_val) / (mu_val + np.sin(mu_val) * np.cos(mu_val))

#BAYESIAN this blacbox function is for bayesian optimization.
def black_box(mu0, mu1, x):
    mu_modified = mu.copy()
    mu_modified[0] = mu0
    mu_modified[1] = mu1

    A_values = A(mu_modified)
    rho_values = rho(x, mu_modified)

    term1 = sum(mu_modified[i]**2 * mu_modified[j]**2 * A_values[i] * A_values[j] * rho_values[i] * rho_values[j] *
                (np.sin(mu_modified[i]+mu_modified[j])/(mu_modified[i]+mu_modified[j]) +
                 np.sin(mu_modified[i]-mu_modified[j])/(mu_modified[i]-mu_modified[j]))
                for i in range(30) for j in range(i+1, 30))

    term2 = sum(mu_modified[j]**4 * A_values[j]**2 * rho_values[j]**2 *
                (np.sin(2*mu_modified[j])/(2*mu_modified[j]) + 1)/2
                for j in range(30))

    term3 = sum(mu_modified[j]**2 * A_values[j] * rho_values[j] *
                (2*np.sin(mu_modified[j])/mu_modified[j]**3 -
                 2*np.cos(mu_modified[j])/mu_modified[j]**2)
                for j in range(30))

    return (term1 + term2 - term3 + 2/15 - 0.0001)

def constraint(x, mu, A_values):
    """Calculate the constraint function value with using bayesian optimization. It returns - maximum since we use SLSQP. """
    # This bound shows parameters change bound. In this case we give +-%10 uncertainity for parameters.
    pbounds = {
        'mu0': (mu[0] * 0.9, mu[0] * 1.1),
        'mu1': (mu[1] * 0.9, mu[1] * 1.1)
    }  # Optimize only selected indices


    #bo_wrapper is used for fixing x. It is necessery for bayesian optimization library that we used. "Learned from chatgpt."
    def bo_wrapper(mu0, mu1):
        return black_box(mu0, mu1, x)

    optimizer = BayesianOptimization(f=bo_wrapper, pbounds=pbounds, verbose = 0)

    # Run Bayesian Optimization
    optimizer.maximize(init_points=5, n_iter=10)
    # Return negative maximum for SLSQP
    return -1 * optimizer.max["target"]

def generate_data(x, radius, mu, A_values, n_samples):
    """Generate data points around current point x within given radius."""
    X = []
    y_obj = []
    y_const = []
    for _ in range(n_samples):
        delta = np.random.uniform(-radius, radius, n)
        x_new = x + delta
        X.append(x_new)
        y_obj.append(objective(x_new))#we didn't use this for now since we don't learn objective function.
        y_const.append(constraint(x_new, mu, A_values))#with here it creates data with using bayesian.
    return np.array(X), np.array(y_obj), np.array(y_const)



def trust_region_optimization(x0, mu, A_values, max_iterations=69, initial_radius=1.0, initial_sample = 30, new_generation=1):
    """Main trust region optimization function with weight decay calibration."""

    x = x0
    radius = initial_radius
    results = []
    penalty_factor = 1000  # Penalty for constraint violations
    X_cumulative = []
    y_obj_cumulative = []
    y_const_cumulative = []

    # Lists to store values for output
    constraint_values = []
    predicted_constraint_values = []
    objective_values = []
    predicted_objective_values = []

    # Generate initial dataset, these cumilative lists are used for learning part.
    X_init, y_obj_init, y_const_init = generate_data(x, radius, mu, A_values, n_samples = initial_sample)
    X_cumulative.extend(X_init)
    y_obj_cumulative.extend(y_obj_init)
    y_const_cumulative.extend(y_const_init)
    count = 0

    #FGN : Evaluate functions at the initial point and store
    current_obj = objective(x0)
    current_cons = constraint(x0, mu, A_values)
    X_cumulative.append(x0)
    y_obj_cumulative.append(current_obj)
    y_const_cumulative.append(current_cons)
    predicted_constraint_value = 0 #these 0's have to be defined. Because in first iteration python simply gives error not defined.
    predicted_objective_value = 0

    for iteration in range(max_iterations):
        # Generate new data points with taking input in function.
        for _ in range(new_generation):
          delta = np.random.uniform(-radius, radius, n)
          x_new = x + delta

          X_cumulative.append(x_new)
          y_obj_cumulative.append(objective(x_new))
          y_const_cumulative.append(constraint(x_new, mu, A_values))

        # kernel definition
        """kernel = C(1.0, (1e-3, 1e3)) * RBF(length_scale=1.0, length_scale_bounds=(1e-2, 1e2))

        # Gaussian Process Model
        constraint_model = GaussianProcessRegressor(kernel=kernel, alpha=1e-6, n_restarts_optimizer=10)


        # fitting gaussian regressor
        constraint_model.fit(X_cumulative, np.array(y_const_cumulative))"""

        #4th degree polynomial regression, you can change degree with changing degree variable in function. In this, there is no weights.
        poly = PolynomialFeatures(degree=4, include_bias=True)
        X_transformed = poly.fit_transform(np.array(X_cumulative))

        # Fit objective and constraint models
        constraint_model = LinearRegression()

        constraint_model.fit(X_transformed, np.array(y_const_cumulative))

        #in this section we have weights. That's the only difference between the previous one.
        """distances = np.linalg.norm(np.array(X_cumulative) - x, axis=1)
        alpha = 0.25  # Decay rate parameter, adjust based on problem
        weights = np.where(distances >= 2*radius, 0, np.exp(-alpha * (distances)**2))
        #weights = weights*(1/np.linalg.norm(weights,ord=np.inf))
        #weights = np.ones(np.shape(weights))
        # Create a dictionary pairing distances with weights
        distance_weight_dict = {f"Data point {i+1}": {"Distance": distances[i], "Weight": weights[i]}
                            for i in range(len(distances))}

        # Log distances and weights
        #for key, value in distance_weight_dict.items():
        #  print(f"{key}: Distance = {value['Distance']:.6f}, Weight = {value['Weight']:.6f}")

        # Transform the data using PolynomialFeatures
        poly = PolynomialFeatures(degree=2, include_bias=True)
        X_transformed = poly.fit_transform(np.array(X_cumulative))

        # Fit objective and constraint models
        constraint_model = LinearRegression()
        constraint_model.fit(X_transformed, np.array(y_const_cumulative), sample_weight=weights)"""

        # simply returns objective function, no longer learning in objective.
        def subproblem_objective(delta):
            #delta_transformed = poly.transform([x + delta])
            #return objective_model.predict(delta_transformed)[0]
            #return rbf_interpolator([x + delta])[0]
            return objective(x + delta)

        #this subproblem is for polynomial regression both with weights and withoout weights
        def subproblem_constraint(delta):
            delta_transformed = poly.transform([x + delta])
            return constraint_model.predict(delta_transformed)[0]

        #subproblem defining function for no degrees gaussian regressor.
        """def subproblem_constraint(delta):
          x_new = x + delta
          delta_array = np.array([x_new])
          delta_array = delta_array.reshape(1, -1)
          return constraint_model.predict(delta_array)[0]"""

        # Solve subproblem
        res = minimize(subproblem_objective, np.zeros_like(x), method='SLSQP',
                      constraints={'type': 'ineq', 'fun': subproblem_constraint},
                      bounds=[(-radius, radius)] * len(x))
        # FGN: Don't you check if minimization is successful (the return code)?
        delta = res.x

        #here is printing part. At first we print current point and curren situations like radius objetive and constraint value.
        print(f"Iteration {iteration}:")
        print(f"Radius: {radius:.6f}")
        print(f"Current Real Objective Value: {current_obj:.6f}")
        print(f"Current Predicted Objective Value: {subproblem_objective(0):.6f}")
        print(f"Current Real Constraint Value: {-1*current_cons:.6f}")
        print(f"Current Predicted Constraint Value: {-1*subproblem_constraint(0):.6f}")
        print("")
        real_constraint_value = constraint(x + delta, mu, A_values)
        predicted_constraint_value = subproblem_constraint(delta)
        real_objective_value = objective(x + delta)
        predicted_objective_value = subproblem_objective(delta)

        #then we print next point values but at this point we don't know it is accepted or not.
        print("")
        print(f"New Real Objective Value: {real_objective_value:.6f}")
        print(f"New Predicted Objective Value: {predicted_objective_value:.6f}")
        print(f"New Real Constraint Value: {-1*real_constraint_value:.6f}")
        print(f"New Predicted Constraint Value: {-1*predicted_constraint_value:.6f}")
        print("")
        # Calculate actual-to-predicted ratio (p_k)
        px = current_obj + penalty_factor * max(0, -1 * current_cons)
        pxx = objective(x + delta) + penalty_factor * max(0, -1 * real_constraint_value)
        mp = subproblem_objective(0) + penalty_factor * max(0, -1 * subproblem_constraint(0))
        mpp = subproblem_objective(delta) + penalty_factor * max(0, -1 * subproblem_constraint(delta))

        pk = (px - pxx) / (mp - mpp) if (mp - mpp) != 0 else 0
        print("px=",px)
        print("mp=",mp)
        print("pxx=",pxx)
        print("mpp=",mpp)

        print("pk=",pk)
        print("")
        print(f"Current Radius: {radius:.6f}")

        if pk >= 0.6:
            radius = min(2 * radius, 2.0)
        elif pk < 0.1:
            radius = max(0.5 * radius, 0.001)
        print(f"New Radius: {radius:.6f}")
        # FGN: Add the new evaluation to the data set
        X_cumulative.append(x+delta)
        y_obj_cumulative.append(real_objective_value)
        y_const_cumulative.append(real_constraint_value)
        print(f"Current Point: {x}")

        # Update solution if improvement is sufficient. Then we print point accepted with also printing new accepted point.
        if pk >= 0.1:
            x = x + delta
            print("Point Accepted")
            print(f"New point x: {x}")
            #FGN : also store the evaluation values here so that you do not re-evalute at x
            current_obj = real_objective_value
            current_cons = real_constraint_value
        print(f"Historical data points: {len(X_cumulative)}")
        print("------------------------")

        # Store values for logging
        constraint_values.append(real_constraint_value)
        predicted_constraint_values.append(predicted_constraint_value)
        objective_values.append(real_objective_value)
        predicted_objective_values.append(predicted_objective_value)

        # Store results
        results.append((iteration, current_obj, x, real_constraint_value, predicted_constraint_value,
                       real_objective_value, predicted_objective_value))

    return results, constraint_values, predicted_constraint_values, objective_values, predicted_objective_values




def save_results(results, filename='optimization_results_polynomial.csv'):
    """Save optimization results to CSV file."""
    with open(filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Iteration', 'Objective Value'] +
                       [f'x{i+1}' for i in range(n)] +
                       ['Real Constraint Value', 'Predicted Constraint Value',
                        'Real Objective Value', 'Predicted Objective Value'])
        for result in results:
            writer.writerow([result[0], result[1]] +
                          list(result[2]) +
                          [result[3], result[4], result[5], result[6]])

def main():
    """Main function to run the optimization."""
    # Calculate A_values once
    A_values = np.array([A(m) for m in mu])

    # Set random seed for reproducibility.
    np.random.seed(1234)

    # Initialize starting point
    x0 = np.random.randn(n)
    print("Initial point:", x0)

    # Run optimization
    results, constraint_values, predicted_constraint_values, objective_values, predicted_objective_values = \
        trust_region_optimization(x0, mu, A_values)

    # Save results
    #save_results(results)
    print("Optimization complete. Results saved to 'optimization_results_polynomial.csv'.")

if __name__ == "__main__":
    main()